---
Name: fulltextsearchconfig
---
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\FullTextSearch\Search\Extensions\SearchUpdater_ObjectHandler

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\FullTextSearch\Search\Queries\SearchQuery:
    calls:
      - [ setHandler, [ '%$SilverStripe\FullTextSearch\Search\Adapters\SolrSearchAdapter' ]]

SilverStripe\Dev\Tasks\MigrateFileTask:
  extensions:
  -  SilverStripe\FullTextSearch\Search\Extensions\DisableIndexingOnFileMigration
